name: flutter_build_version
description: Flutter/Dart version library
version: 0.0.1

environment:
  sdk: ">=2.17.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0