name: flutter_build_version_generator
description: Build_runner generator for Flutter version
version: 0.0.1

environment:
  sdk: ">=2.17.0 <5.0.0"

dependencies:
  build: ">=3.0.2 <5.0.0"
  source_gen: ">=3.1.0 <5.0.0"
  analyzer: ">=8.0.0 <10.0.0"
  flutter_build_version:
    git:
      url: https://github.com/kilroy80/flutter_build_version_package
      path: "flutter_build_version"

dev_dependencies:
  build_runner: ^2.8.0