name: flutter_build_version_example
description: A simple command-line application.

environment:
  sdk: ">=2.17.0 <5.0.0"

dependencies:
  flutter_build_version:
    path: ../../flutter_build_version

dependency_overrides:
  flutter_build_version:
    path: ../../flutter_build_version
  flutter_build_version_generator:
    path: ../../flutter_build_version_generator

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  flutter_build_version_generator:
    path: ../../flutter_build_version_generator